# Generated by Django 2.2.3 on 2019-07-09 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pracapp.TimeStampedModel')),
                ('names', models.CharField(max_length=20)),
                ('slug', models.CharField(max_length=10, unique=True)),
            ],
            bases=('pracapp.timestampedmodel',),
        ),
    ]
