# Generated by Django 2.2.3 on 2019-07-09 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pracapp', '0002_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='names',
            new_name='name',
        ),
    ]
